Added Work And About Section
gisachris/Portfolio-Site pull request #4
Opened 2023-03-28 17:35 UTC by gisachris

in this PR i added the following:
-Added work section using both grid and flexbox
-added about section using flexbox
-Added button interactions ie:hover,active

2023-03-28 19:16 UTC, amon-cofie requested changes
Hi @gisachris , 👋   

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

<img src="https://media3.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

🚀 Great effort on the styling
🚀 Good job ensuring no linter errors
🚀 Your pull request summary is descriptive

## Required Changes ♻️

You have indeed put great effort into this project. However, your design does not quite look the same as the figma template but I believe there are only a few things you need to work on and it will look just like the template. Check the screenshots below: 

Your design: 
![image](https://user-images.githubusercontent.com/107795045/228342539-ccfb7eed-80ce-4177-b128-f51bb09855e7.png)

Figma design: 
![image](https://user-images.githubusercontent.com/107795045/228342758-d445c1b5-e598-4db9-bab8-8cef88069245.png)

Your design:
![image](https://user-images.githubusercontent.com/107795045/228343188-07c422a5-eb5f-4f33-876c-c5514e32784b.png)

Figma design: 
![image](https://user-images.githubusercontent.com/107795045/228343476-c4b9c82e-02f4-4b50-a1f0-c25f38ec8edd.png)

I suggest that you pay attention to the way you use the view heights unit ```vh```. I am available on slack if you need help with some of these comments.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 19:16 UTC, amon-cofie commented on index.html
>      </div>
I can see that you put a lot of effort into this and you have done a pretty good job. However, I believe putting this section in a section tag instead of a div would be more semantically sound. 👍 Also, you don't need multiple header tags in your HTML. The header doesn't have to be used to present the main idea of a section. You will probably find it more semantically sound if you organize your page in the following way: 
```
<header></header>
<main>
   <section></section>
   <section></section>
   <section></section>
</main>
<footer></footer>
```

2023-03-28 19:16 UTC, amon-cofie commented on index.html
> +          Get my resume
Please consider putting the about section into a section tag instead of a div tag. This is more semantically sound. 👍 
You can put the sub-sections of the about section into different other semantic tags other than the section tag to improve upon the semantic scores of your page.

2023-03-28 19:16 UTC, amon-cofie commented on index.html
> +        </section>
You have done well in putting the various technologies into lists but also consider putting the technology categories themselves, ie. Languages, frameworks and skills, into A list as well. This will improve upon the semantics of your page. 👍

2023-03-29 13:58 UTC, gisachris commented on index.html
>      </div>
thank you @amon-cofie for the review.
in this branch 's submited for review i have done the following:
-change the background to fit figma design.
-change page semantics to suggested format
<header></header>
<main>
   <section></section>
   <section></section>
   <section></section>
</main>
<footer></footer>
-on about section make list headers into there own list for better semantics as requested
-change page elements to use proper measurements ex: fonts to use px or ems

2023-03-29 13:59 UTC, gisachris commented on index.html
> +        </section>
thank you @amon-cofie for the review.
in this branch 's submited for review i have done the following:
-change the background to fit figma design.
-change page semantics to suggested format
<header></header>
<main>
   <section></section>
   <section></section>
   <section></section>
</main>
<footer></footer>
-on about section make list headers into there own list for better semantics as requested
-change page elements to use proper measurements ex: fonts to use px or ems

2023-03-29 14:23 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @gisachris , 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 14:47 UTC, merged